---

# Prepare KVM and Check Images
- include: prep_hypervisor_and_vms.yml
  when: hypervisor is defined

# Copy and Resize cow2 image to target host
- include: copy_and_resize_qcow.yml
  when: hypervisor is defined

# Cloud-init files section... Important: don't change the names of the files!
- include: cloud_init_files.yml
  when: hypervisor is defined

# Define and create guest VMs
- include: define_and_create_vm.yml
  when: hypervisor is defined

#remove cloud_init media iso image
- include: cloud_init_files_remove.yml
  when: hypervisor is defined

