# preparing kvm and checking current vms

- name: Pull facts on hypervisor
  action: setup
  delegate_to: "{{ hypervisor }}"
  when: hypervisor is defined

- name: Install additional packages to modify qcow image and run as VM - RedHat Host
  yum: name={{ item }} state=present
  with_items:
   - qemu-kvm
   - libvirt
   - bridge-utils
   - libguestfs-tools
   - libvirt-python
   - genisoimage
  when:
    - ansible_os_family == "RedHat"
    - hypervisor is defined
  delegate_to: "{{ hypervisor }}"

- name: Checking OS distribution
  fail: 
    msg: "Only RedHat distribution is supported"
  delegate_to: "{{ hypervisor }}"
  when:
    - ansible_os_family != "RedHat"
    - hypervisor is defined

- name: Check libvirtd service is running
  service:
    name: libvirtd
    state: started 
  delegate_to: "{{ hypervisor }}"

- name: List the Virtual Machine
  virt: command=list_vms
  register: virt_vms
  delegate_to: "{{ hypervisor }}"
  when: hypervisor is defined

- name: Checking out if the libvirt domains are already defined ( true will fail this task )
  fail: msg="The VM {{ inventory_hostname }} is already defined on this hypervisor."
  when: inventory_hostname in virt_vms.list_vms

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
