---
#- hosts: nservers
#  remote_user: root
#  gather_facts: no
#  roles:
#    - dom-create

#- hosts: vsd
#  remote_user: root
#  gather_facts: no
#  roles:
#    - dom-create

- hosts: vsc
  remote_user: root
  gather_facts: no
  roles:
    - vsc-create
