---
galaxy_info:
  author: Mauricio Rojas
  description: Deploy Kubernetes Cluster with Nuage on a KVM hypervisor
  license: MIT
  min_ansible_version: 1.4
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - networking
dependencies: []
